# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HHPublishDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HHPublishDemo

pod 'Masonry'

  target 'HHPublishDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HHPublishDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
